### ISSUE TITLE
Could you share these two files --FRNet_PATH ，PATH_TRAIN ，Thanks

### ISSUE THREAD

**Issue by Cynthialss** [vrkh1996/IPU-Net#2]
Could you share these two files --FRNet_PATH ，PATH_TRAIN ，Thanks

**Comment by vahid0001** [comment]
model: https://drive.google.com/drive/folders/12aMYASGCKvDdkygSv1yQq8ns03AStDO_
dataset: https://academictorrents.com/details/535113b8395832f09121bc53ac85d7bc8ef6fa5b
